### ISSUE TITLE
[Feat] 카테고리 메인/편집 세부적 기능

### ISSUE THREAD

**Issue by GeonHyeongKim** [MUCH-MORE-MONEY/iOS#115]
## 📌  Feature Issue

- 메인 화면
- 편집 화면

## 📝  To-do

- [ ] 카테고리 메인에 정렬 제거
- [ ] 카테고리 메인에 상위에 Header 추가
- [ ] 카테고리 편집 API 연결
- [ ] 카테고리 편집 Footer에 편집 버튼
- [ ] 카테고리 편집 하위에 상위 편집 버튼
- [ ] Empty case
- [ ] 통계에 Width를 못잡는 문제
