### ISSUE TITLE
[Feat] 배포전 버그 픽스

### ISSUE THREAD

**Issue by jwoo820** [MUCH-MORE-MONEY/iOS#133]
## 📌  Feature Issue

배포전 버그 픽스
## 📝  To-do

- [ ] 푸쉬 넛징
- [x] 경제활동 디테일 -> 편집에서 이미지가 작아지는 현상
- [x] 경제활동 편집 & 추가 -> textField firstResponder 추가
- [x] 경제활동 디테일 -> 편집으로 넘어갈때 카테고리 필드가 넘어가지 않는 문제
- [x] 요일별 알림 cell의 사이즈가 동적으로 변하지 않는 문제
- [x] 경제활동 편집 & 추가 -> 카테고리 cell 디자인 변경
- [x] 푸시 알림 뱃지가 앱을 클릭해도 남아있는 문제
- [x] 예산 -> 카테고리 -> 상세 뷰 에서 pageControl을 통하여 뷰를 전환할때 title이 고정인 문제
- [x] 푸시 알림 설정 -> 시간 설정 -> 이미 데이터가 있음해도 현재시간으로 초기화되는 문제
