### ISSUE TITLE
[Feat] 통계 메인 (1) - UI (feat, 카테고리 제외)

### ISSUE THREAD

**Issue by GeonHyeongKim** [MUCH-MORE-MONEY/iOS#81]
## 📌  Feature Issue

<img width="281" alt="image" src="https://github.com/MUCH-MORE-MONEY/iOS/assets/48436020/5813360f-066d-4b5a-a572-d55e1beeb34e">

## 📝  To-do

- [ ] 상위 달력 Picker UI
- [ ] 상위 만족도 UI
- [ ] 카테고리 UI
- [ ] 상위/하위 활동 UI
- [ ] 만족도 모아보기 UI
